### PR TITLE
Turn your key Sir!

### PR DESCRIPTION
**Pull request by Nickvr628**
Don't you hate having to run all the way back to your office to swipe for red alert? Maybe the bridge is the only safe place left? No time to run to another authenticator? Fear not, because now there are TWO keycard authenticators on the bridge, spaced apart so you can see the other person but cannot run from one to the other. If you are crafty, you might be able to find a way to solo-activate red alert, but your best bet is to just have two people there.

image

Also you get to shout at people to TURN YOUR KEY and hold them at gunpoint until they unlock the BSA when Centcom sends Emergency Wartime Orders.

:cl:  
add: There are now two authenticators on the bridge so two Heads (or a crafty single head) can activate red alert from the same location. 
/:cl:

### CODE REVIEW

**Comment by nichlas0010** [comment]
bad

**Comment by Nickvr628** [comment]
why nich, why is it bad that now two heads can initiate a red alert without having to run laps around the station?

**Comment by Kmc2000** [comment]
use a portal gun
you now have solo redalert

**Comment by Nickvr628** [comment]
Yeah but that requires some effort and ingenuity to do, so it is fair game. No different than firing one into the HOP office and bridge.

**Comment by MegaEmpirical** [comment]
You'd think you would be able to red alert on the bridge anyway. It's the damn bridge.

**Pull request merged**
