### PR TITLE
Pet carriers can now carry people

### PR DESCRIPTION
**Pull request by Nickvr628**
Let the shenanigans begin

### CODE REVIEW

**Comment by jcatjmeow** [comment]
I dislike this

**Comment by alexkar598** [comment]
I'm just...no just no.

**Comment by Nickvr628** [comment]
What the hell why not

**Comment by Trustback** [comment]
That's even worse than adding what age you want to be into the magic mirror.

**Comment by jcatjmeow** [comment]
1 downvote every 7.5 seconds before it was closed, impressive.

Whats not impressive is you +1'd your own pr, disgusting

**Pull request closed without merging**
