### PR TITLE
supermatter is more extreme but has the exact same balance as before as everything was buffed equally

### PR DESCRIPTION
**Pull request by Nickvr628**
what the title says. the supermatter is now more extreme by a factor of 10.

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Stop shitpring

**Comment by Nickvr628** [comment]
this isn't shitposting

**Comment by alexkar598** [comment]
WILL. YOU. STOP. WITH. THE. SHIT. WEBEDIT. PRS. THAT. YOU. DIDNT. TEST?

**Comment by Nickvr628** [comment]
I did test this one actually I have been working on it all day

**Comment by jcatjmeow** [comment]
Bruh you typed a zero after every number how did that take you all day

**Comment by Nickvr628** [comment]
I had to do decimal math too

**Comment by jcatjmeow** [comment]
No, you didn't

**Comment by Nickvr628** [comment]
image

**Comment by jcatjmeow** [comment]
So figuring out what 2.5×10 is took you all day, I see

**Comment by Nickvr628** [comment]
well not JUST that one

**Comment by Lostlarry** [comment]
did you also increase the temperature on whole station by 360 kelvins?

**Pull request closed without merging**
