### PR TITLE
Paramedic Hardsuit (non-printable version)

### PR DESCRIPTION
**Pull request by Nickvr628**
A new Paramedic Hardsuit is available ~~through RnD and buildable at the medical fabricator~~ to paramedics. Designed for when paramedics have to go to a dangerous location to save people, like space, the front line of a blob fight, or Reebe. Has slightly better armor than the normal medical hardsuit, but does not have virus or rad protection. 

image

:cl:  
rscadd: A hardsuit for Paramedics. Has slightly better armor than the medical hardsuit but loses out on some biological and radiological protections. Good for rescuing people from dangerous situations
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
quick give me a example of any other hardsuit that can be made

**Comment by Smudged** [comment]
Don't make it printable at ANY protolathes, you don't want every greytider on station to break down your doors to get a free hardsuit, there was a reason the flight suit which was also a printable hardsuit was removeed at one point.

Give the paramedics the hardsuit, and only 1 of them to save people from space and stuff.

(Also on a personal point, when you get a chance post the pictures of the side + back sprite)

**Comment by Nickvr628** [comment]
image

image

I will think about making one start in the paramedic locker instead of being researched and printed.

**Comment by MegaEmpirical** [comment]
A printable suit is crazy talk, but otherwise I am very on board with this. Trying to get an EVA suit to save people has been a huge pain in my fucking ass.

**Comment by HomocidlePancakes** [comment]
>Don't make it printable at ANY protolathes, you don't want every greytider on station to break down your doors to get a free hardsuit, there was a reason the flight suit which was also a printable hardsuit was removeed at one point.

Lol. Flightsuits were removed due to code reasons, not balance. Do your research before posting nerd.

**Comment by Nickvr628** [comment]
The paramedic hardsuit now starts in the office and there is no way to get more of them.

**Comment by Smudged** [comment]
> > Don't make it printable at ANY protolathes, you don't want every greytider on station to break down your doors to get a free hardsuit, there was a reason the flight suit which was also a printable hardsuit was removeed at one point.
> 
> Lol. Flightsuits were removed due to code reasons, not balance. Do your research before posting nerd.

Well, I still don't like the idea of mass-printable hardsuits, and since the flight suit didn't come back, It's for the best

**Comment by Nickvr628** [comment]
I accidentally resolved the merge conflicts backwards

**Comment by Nickvr628** [comment]
image
fuck I broke it

**Comment by Nickvr628** [comment]
Nick cannot into version control confirmed

**Comment by nichlas0010** [comment]
feel free to reopen this once the conflicts have been fixed

**Comment by MegaEmpirical** [comment]
Nooooooo

**Pull request closed without merging**
