### PR TITLE
Fixes station allignment

### PR DESCRIPTION
**Pull request by Nickvr628**
Centcom had the station perform an orbital correction burn and now it is in the center of space again.

:cl:  
bugfix: the station is no longer un-centered. 
/:cl:

### CODE REVIEW

**Comment by Ktlwjec** [comment]
wtf where are the images??

**Comment by Nickvr628** [comment]
use the mapdiff render bot you dengenerate

**Comment by thehighwayman** [comment]
looks ugly tbh

**Comment by Ktlwjec** [comment]
serious note: can you use an actually up-to-date map please?

**Comment by Nickvr628** [comment]
This is the most up to date map, I forked the repository right before making the PR

**Comment by Ktlwjec** [comment]
image
are you sure?

**Comment by thehighwayman** [comment]
travis failed hahaha

**Comment by nichlas0010** [comment]
@Nickvr628 mapmerge converts it from DMM format to TGM, which is necessary since otherwise the .dmm file will have a billion line changes everytime something changes

**Comment by Nickvr628** [comment]
Oh and for the center of the station part, one main thing was that the map was aligned so the toxins bomb target was the rightmost part of the station as far as centering goes, which pushed the entire map to the left unnecessarily. I recentered it so the distance to the edge was measured from arrivals and escape, instead of arrivals and the toxins test site.

It gives more room on the left side of the station for the pilotable shuttles like pirates, etc while still leaving a good amount of room to the right of the toxins test target before the map ends.

**Comment by Nickvr628** [comment]
@Ktlwjec if you could look at unfucking this like you said in the discord at your convenience, input would be appreciated.

Or, worst comes to worst, I start over from scratch again since nich decided to fuck my PR with his mirror memes.

**Comment by Ktlwjec** [comment]
just get a new map copy, copy it a few tiles to the right, and add that to this pr :thinking:

**Comment by Nickvr628** [comment]
damn I was afraid you would say that. oh well

**Comment by Nickvr628** [comment]
OK MERGE THIS SHIT

**Pull request merged**
