### PR TITLE
Ashwalkers now breathe N2 with special lungs!

### PR DESCRIPTION
**Pull request by Ludox235**
Ashwalkers now got something MORE special than shitty legs and draconic language and it is new lungs!

Fixes issue #4978 

inb4 i fucked up somewhere horribly (wouldn't be surprised)

:cl:
rscadd: Grey lungs for the ashwalkers. If you CPR someone with grey lungs whithout having them yourselves, you choke them. 
tweak: Ashwalkers actually breathe n2 now from the grey lungs they got
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
it was right the first time, you forgot to tick the file in dream maker/commit the `yogstation.dme` file

**Comment by HomocidlePancakes** [comment]
They shouldn't be able to do CPR on non-ashwalkers (or choke filthy oxygen breathers with CRP lol)

**Comment by Ludox235** [comment]
> 
> 
> it was right the first time, you forgot to tick the file in dream maker/commit the `yogstation.dme` file

Oh lmao



> 
> 
> They shouldn't be able to do CPR on non-ashwalkers (or choke filthy oxygen breathers with CRP lol)

I'll try to make so you can't

**Comment by fluffe9911** [comment]
Choking people who breath oxygen with cpr sounds funny though lol

**Comment by Ludox235** [comment]
> 
> 
> Choking people who breath oxygen with cpr sounds funny though lol

That's what i'm doing right now lmao

**Comment by Time-Green** [comment]
they'd actually be better at cpr since they don't consume the oxygen in their breath

**Comment by Time-Green** [comment]
they'd actually be better at cpr since they don't use the oxygen in their breath

**Comment by MegaEmpirical** [comment]
Time is correct.

I don't know how it works mechanically but it should be based on whatever you're inhaling.... However, using CPR works on plasmamen so it's probably not what's in the air.

**Comment by MegaEmpirical** [comment]
A note if someone does try to apply this to lizards: after a discussion, I decided that whilst it would be cool and not a huge buff to make lizards be able breath on lavaland, the effective bonus storage space is too strong. So if lizards get N2 lungs, there N2 requirement needs to be increased so that they can't breath on lavaland.

Effectively they'd no longer be adapted to  breathing in the low pressure environment much like how they can't do ashstorms.

**Comment by boodaliboo** [comment]
no

**Comment by HomocidlePancakes** [comment]
Lizards should start with N2 internals now then.

**Comment by Ludox235** [comment]
I believe giving normal lizards N2 breathing but needing more so they don't survive on Lavaland a bit too much. If I make them need more N2 they will need to put on internals, internals which will empty incredibly quickly because they will dispense over 60kpa. Unless I make tanks that are bigger in the inside than the outside, where people could easily abuse it and fill it with oxygen to have basically infinite internals.

**Comment by MegaEmpirical** [comment]
I'm not familiar with lavaland atmos so I wasn't sure what the threshold would be, it's entirely possible it's not a reasonable amount. Just a suggestion.

As for Pancake: Station side lizards wouldn't need internals since the station is 80% Nitrogen.

**Comment by Ludox235** [comment]
> 
> 
> I'm not familiar with lavaland atmos so I wasn't sure what the threshold would be, it's entirely possible it's not a reasonable amount. Just a suggestion.
> 
> As for Pancake: Station side lizards wouldn't need internals since the station is 80% Nitrogen.

The amount of nitrogen on lavaland is around 60% IIRC

**Comment by MegaEmpirical** [comment]
That's only one part of the puzzle. What's the pressure too?

**Pull request merged**
