### PR TITLE
New contraband poster [Council Request]

### PR DESCRIPTION
**Pull request by Nickvr628**
image

Added a new poster

image

:cl:  
rscadd: New contraband poster at the request of yogstation staff.
/:cl:

### CODE REVIEW

**Comment by AsV9** [comment]
wrong sprite though

**Comment by Nickvr628** [comment]
I am not using the neonazi version that was made as a joke

**Comment by Oakboscage** [comment]
> I am not using the neonazi version that was made as a joke

Well maybe you should

**Comment by alexkar598** [comment]
Stupid PR

**Comment by Nickvr628** [comment]
by far my lowest effort PR. amazing

**Pull request merged**
